### ISSUE TITLE
Response files not supported by `ar` on macOS

### ISSUE THREAD

**Issue by jchavarri** [ocaml/ocaml#12070]
The diversion introduced in https://github.com/ocaml/ocaml/pull/9492 to handle linking with long argument lists does not seem to work on macOS, or at least in recent versions of this OS.

This can be tested by running:
```bash
$ touch responsefile
$ ar -rcu lib.a @responsefile
ar: @responsefile: No such file or directory
```

The issue was found while trying to add some synthetic benchmarks for macOS in Dune. The specific CI error can be found [here](https://github.com/jchavarri/dune/actions/runs/4315316097/jobs/7529524309#step:15:22), reproducing it below for conveniency and future record:
```
(cd _build/default && /Users/runner/work/dune/dune/_opam/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62@67@69-40 -strict-sequence -strict-formats -short-paths -keep-locs -alert -unstable -g -a -o bench/synthetic/test.cmxa bench/synthetic/.test.objs/native/test.cmx bench/synthetic/.test.objs/native/test__M_999.cmx bench/synthetic/.test.objs/native/test__M_998.cmx ...bench/synthetic/.test.objs/native/test__M_1.cmx)
ar: @/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/build_6ab340_dune/camlresp8ab5ca: No such file or directory
File "_none_", line 1:
Error: Error while creating the library bench/synthetic/test.a
```

I could also reproduce locally on my macOS device. Another data point are the [docs for `ar` command on macOS](https://www.unix.com/man-page/osx/1/ar/), which don't include any reference to `@FILE`.

Aside from the above but still related, it seems that the max length of command line arguments was increased in a version of macOS released [a few months after the diversion was introduced](https://en.wikipedia.org/wiki/MacOS_Big_Sur), from the [Big Sure 11.0.1 release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes):

> The `kern.argmax` limit has been increased, allowing programs to receive longer argument lists.

On my device (macOS Ventura 13.2.1) I get a limit of `2^20`:

```
$ getconf ARG_MAX
1048576
```

I believe similar upgrades have been done in the Linux kernel.

Considering the above:
- Response files might not be supported in all platforms where the OCaml compiler runs
- Max length args is a moving target, as operating systems continue to evolve

I wonder if the diversion could be modified to become opt-in, and also defer to users to define the argument length at which it kicks in?

More references:
- https://gitlab.kitware.com/cmake/cmake/-/issues/16731
- https://developer.apple.com/forums/thread/95831

**Comment by nojb** [comment]
If I'm understanding correctly, the BSD version of `ar` does not support response files, so supposedly it is not just Darwin that is affected. In that case, the easiest would be to disable the use of response files on Darwin/BSD altogether.

cc @hannesm as our resident BSD user :)

**Comment by rgrinberg** [comment]
> so supposedly it is not just Darwin that is affected. In that case, the easiest would be to disable the use of response files on Darwin/BSD altogether

Note that it's possible to use the GNU toolchain on these systems as well. So this disabling should at least be configurable.

**Comment by hannesm** [comment]
> If I'm understanding correctly, the BSD version of `ar` does not support response files, so supposedly it is not just Darwin that is affected. In that case, the easiest would be to disable the use of response files on Darwin/BSD altogether.
> 
> cc @hannesm as our resident BSD user :)

Indeed, there's no support for them on FreeBSD. I guess I never ran into the limit that a responsefile was used.

**Comment by avsm** [comment]
I think this needs to be a feature check rather than an OS decision.  OpenBSD uses clang as the base compiler on most architectures, which does support response files in `ar`.

**Comment by nojb** [comment]
> I think this needs to be a feature check rather than an OS decision. OpenBSD uses clang as the base compiler on most architectures, which does support response files in `ar`.

Agree: the fix in #12075 checks whether `ar` supports the feature at configure time.

**Comment by nojb** [comment]
Fixed in #12075

**Comment by dboris** [comment]
I attempted to backport the fix for this issue to the 4.14 branch but was surprised that the issue was not fixed. So I double checked by trying to build a large library with the 5.2.0 compiler and the issue is still present there. Running `configure` on trunk, then checking:
```
checking for archiver @FILE support... no
...

cat utils/config.generated.ml | grep ar_supports
let ar_supports_response_files = true
```
That's on a macOS Monterey 12.7.5, Intel CPU.

**Comment by nojb** [comment]
@dboris could you apply the following patch, regenerate `./configure` using `tools/autogen` and re-run `./configure` and report back what is printed in the line `lt_cv_ar_at_file=...`? Thanks!

```diff
diff --git a/configure.ac b/configure.ac
index 7a07b367de..ce0aad5f0a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -692,6 +692,8 @@ ocamlsrcdir=${ocamlsrcdir%X}

 # Whether ar supports @FILE arguments

+AC_MSG_NOTICE([lt_cv_ar_at_file=$lt_cv_ar_at_file])
+
 AS_CASE([lt_cv_ar_at_file],
   [no], [ar_supports_response_files=false],
   [ar_supports_response_files=true])
```

**Comment by dboris** [comment]
```
configure: lt_cv_ar_at_file=no
```

**Comment by nojb** [comment]
So far everything is as expected. Can you post the result of the following command?
```
grep ar_supports config.log
```
(after running `./configure`)

**Comment by dboris** [comment]
```
ar_supports_response_files='true'
```

**Comment by nojb** [comment]
OK, that's wrong :) Mmph, can you try the following patch?
```diff
diff --git a/configure.ac b/configure.ac
index 7a07b367de..41032993ec 100644
--- a/configure.ac
+++ b/configure.ac
@@ -692,7 +692,7 @@ ocamlsrcdir=${ocamlsrcdir%X}

 # Whether ar supports @FILE arguments

-AS_CASE([lt_cv_ar_at_file],
+AS_CASE([$lt_cv_ar_at_file],
   [no], [ar_supports_response_files=false],
   [ar_supports_response_files=true])
```

**Comment by dboris** [comment]
Now it's good:
```
ar_supports_response_files='false'
```

**Comment by nojb** [comment]
Thanks, PR in #13209.

**Comment by dboris** [comment]
Thanks. I will submit a PR for the backport after I double check it.

**Comment by nojb** [comment]
Sounds good, thanks!
