### ISSUE TITLE
Different evaluation order for `match ... with ...` and `match .. with .. | exception ...`.

### ISSUE THREAD

**Issue by mattiasdrp** [ocaml/ocaml#12438]
```ocaml
let f ci =
  let _ =
    match input_char ci with
    | 'r' -> (
        match (input_char ci, input_char ci) with
        | 'e', 'd' -> Format.eprintf "Saw red@."
        | _ -> Format.eprintf "Saw nothing@."
        | exception End_of_file -> Format.eprintf "Saw nothing@.")
    | _ -> ()
  in
  close_in ci

let () = f (open_in "test")
```

Content of `test` file:
```
redred
```

> \>ocaml main.ml

Outputs

> Saw nothing

If I remove the ` | exception End_of_file -> Format.eprintf "Saw nothing@."` line, it outputs

> Saw red

**Comment by lthls** [comment]
What happens is that depending on whether the pattern matching contains an exception clause or not, the strategy for compiling the whole match changes and the evaluation order for the tuple (which is unspecified) is inverted.

My opinion is that it is a bug, and that evaluation order should be consistent, so I'll try to submit a fix, but if you have this problem in real code you should really make the evaluation order explicit.
The evaluation order most consistent with the rest of the compiler is the one that would produce `Saw nothing` here, which is probably not what you want.

**Comment by mattiasdrp** [comment]
Hey Vincent, thanks for the answer :-)
I agree, this is a bug in my opinion. Pattern matching is supposed to be read top to bottom and trigger on the first pattern that matches our current value. This is not the case anymore when exceptions are matched in it and there's no way to know this.

**Comment by lthls** [comment]
The problem is not the pattern-matching in itself, it's that if you do `let c1, c2 = (input_char ci, input_char ci) in ...` then `c1` will usually contain the second character and `c2` the first one. It's only due to some tricky details that in this case, when there is no exception handler, the order is reversed and the first field of the tuple contains the first character.

**Comment by mattiasdrp** [comment]
Oh, okay, I see, didn't think about that in this way. Anyway, I fixed it on my side by using `really_input_string` :D

**Comment by gasche** [comment]
I can still reproduce the issue in trunk (in the toplevel): adding an `exception` clause changes the evaluation order:

```ocaml
# match print_endline "foo", print_endline "bar" with _ -> ();;
foo
bar
- : unit = ()
# match print_endline "foo", print_endline "bar" with _ -> () | exception _ -> ();;
bar
foo
- : unit = ()
```

**Comment by gasche** [comment]
@lthls proposed a fix in #12440, but for now there is no consensus to change the evaluation order due to the risk of breaking some programs that were silently relying on the previous evaluation order. I am closing this issue as "won't fix", unfortunately.

**Comment by dbuenzli** [comment]
I think it would be nice to add a "Language pitfalls" chapter in part 2 of the manual that collects the few language warts OCaml has.

**Comment by lthls** [comment]
Note that since this issue was open, the syntax for effect handlers was added, so now having either an effect clause or an exception clause will make the evaluation order right-to-left.
