### ISSUE TITLE
Side effect in type expansion leads to improper treatment of type constraints

### ISSUE THREAD

**Issue by phink** [ocaml/ocaml#13230]
### Minimal example

If we compile the following example using OCaml 5.2.0:

```ocaml
module S (M : sig
  type t
end) =
struct
  type 'a u = M.t constraint 'a = M.t

  let id x : M.t u = x
end

module A = S (struct
  type t = unit
end)

module B = S (struct
  type t = unit A.u
end)
```

The compiler crashes with the following error:

```
Fatal error: nondep_supertype not included in original module type
Fatal error: exception Misc.Fatal_error
```

**Comment by tmarti2** [comment]
I have 2 similar errors with OCaml 4.14.2, but no idea of which part of my code raises this. Here is the full stacktrace :
```
File "src/.toto.objs/native/_unknown_", line 1, characters 0-0:
>> Fatal error: nondep_supertype not included in original module type
Fatal error: exception Misc.Fatal_error
Raised at Misc.fatal_errorf.(fun) in file "utils/misc.ml", line 22, characters 14-31
Called from Misc.fatal_error in file "utils/misc.ml" (inlined), line 26, characters 22-43
Called from Typemod.type_one_application in file "typing/typemod.ml", line 2361, characters 16-101
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_structure.type_str_item in file "typing/typemod.ml", line 2554, characters 10-202
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.run in file "typing/typemod.ml", line 2809, characters 6-42
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_implementation.(fun) in file "typing/typemod.ml", line 3000, characters 8-38
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Compile_common.typecheck_impl in file "driver/compile_common.ml", line 103, characters 2-131
Called from Compile_common.implementation.(fun) in file "driver/compile_common.ml", line 121, characters 18-44
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Compenv.process_action.impl in file "driver/compenv.ml", line 632, characters 4-69
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Compenv.process_deferred_actions in file "driver/compenv.ml", line 719, characters 2-61
Called from Optmaindriver.main in file "driver/optmaindriver.ml", line 53, characters 6-163
Re-raised at Location.report_exception.loop in file "parsing/location.ml", line 938, characters 14-25
Called from Optmaindriver.main in file "driver/optmaindriver.ml", line 136, characters 4-35
Called from Optmain in file "driver/optmain.ml", line 2, characters 7-57

File "src/.toto.objs/byte/_unknown_", line 1, characters 0-0:
>> Fatal error: nondep_supertype not included in original module type
Fatal error: exception Misc.Fatal_error
Raised at Misc.fatal_errorf.(fun) in file "utils/misc.ml", line 22, characters 14-31
Called from Misc.fatal_error in file "utils/misc.ml" (inlined), line 26, characters 22-43
Called from Typemod.type_one_application in file "typing/typemod.ml", line 2361, characters 16-101
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_structure.type_str_item in file "typing/typemod.ml", line 2554, characters 10-202
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.type_struct in file "typing/typemod.ml", line 2802, characters 10-44
Called from Typemod.type_structure.run in file "typing/typemod.ml", line 2809, characters 6-42
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_implementation.(fun) in file "typing/typemod.ml", line 3000, characters 8-38
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Compile_common.typecheck_impl in file "driver/compile_common.ml", line 103, characters 2-131
Called from Compile_common.implementation.(fun) in file "driver/compile_common.ml", line 121, characters 18-44
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Compenv.process_action.impl in file "driver/compenv.ml", line 632, characters 4-69
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Compenv.process_deferred_actions in file "driver/compenv.ml", line 719, characters 2-61
Called from Maindriver.main in file "driver/maindriver.ml", line 34, characters 6-147
Re-raised at Location.report_exception.loop in file "parsing/location.ml", line 938, characters 14-25
Called from Maindriver.main in file "driver/maindriver.ml", line 110, characters 4-35
Called from Main in file "driver/main.ml", line 2, characters 7-54
```
Is there a way to narrow it down to locate the code which causes this crash ?

**Comment by smuenzel** [comment]
I believe this is fixed by: https://github.com/ocaml/ocaml/pull/11648

@tmarti2, do you also have an example code section that causes the error?

**Comment by tmarti2** [comment]
I don't sorry. From what I remember it was also caused by a similar code, with modules and constraints, but I changed my implementation since then :/

**Comment by clementblaudeau** [comment]
The problem is still there in 5.3. It comes from a weird interaction of avoidance and type constraints. The example can be somewhat simplified to:

```ocaml
module F (Y : sig type t end) = struct
  type 'a u = Y.t constraint 'a = Y.t
  let id x : Y.t u = x
end

type 'a v = int

(* Anonymous functor call - crash *)
module C = F(struct type t = bool v end)
``` 

When facing signature avoidance errors, it is interesting to compare the output of replacing the anonymous functor call by an anonymous open: 

```ocaml
(* Anonymous open - type error *)
module C' = struct
  open (struct
    module Arg = struct type t = bool v end
  end)
  include F(Arg)
end
```

```
Error: Signature mismatch:
       ...
       Values do not match:
         val id : Arg.t -> Arg.t
       is not included in
         val id : Arg.t -> Arg.t
       The type Arg.t -> Arg.t is not compatible with the type Arg.t -> Arg.t
       Type Arg.t = int is not compatible with type Arg.t = int
```

In both cases the problem is the same (but the second one produces a type error instead of crashing): the signature obtained after avoiding the anonymous parts is not deemed a supertype of the original signature. It seems to come from a bad propagation of type constraints ? I'll try to investigate

**Comment by clementblaudeau** [comment]
Ok it turns out to be not related to avoidance, but more to the handling of type constraints ?

This minimized example makes my top-level `ocaml` fail : 
```ocaml
type _ t    = int
type bool_t = bool t (* actually int *)
type 'a u   = 'a constraint 'a = bool_t (* also int *)
let fails : (bool t) u =  (42 : bool_t u ) ;;
```
with this (cryptic) error message: 
```
Error: Values do not match:
         val fails : bool t u
       is not included in
         val fails : bool t u
       The type bool t u = int is not compatible with the type bool t u = int
```
(Turns out that the top-level rechecks subtyping between the inferred type (`val fails : bool t u`) and itself).  
To have `ocamlc` fail, I need to force this subtyping check by, for instance, puting the problematic types inside value declarations : 
```ocaml
type _ t    = int
type bool_t = bool t (* actually int *)
type 'a u   = 'a constraint 'a = bool_t (* also int *)
module type S1 = sig val x : bool t u (* = int *) end
module type S2 = sig val x : bool_t u (* = int *) end
module Fail = functor (Y:S2) -> (Y:S1)
```

So this problem has actually nothing to do with functor call or avoidance, it just happened that `nondep_supertype` was building a *valid* signature that triggers the bug. I suspect a problematic handling of levels with type constraints.

**Comment by phink** [comment]
@clementblaudeau Thank you a lot for the detailed answers and the minimal examples.

> So this problem has actually nothing to do with functor call or avoidance, it just happened that nondep_supertype was building a valid signature that triggers the bug. I suspect a problematic handling of levels with type constraints.

Should I rename the issue accordingly?

**Comment by clementblaudeau** [comment]
I think so ? A bit more investigation with @samsa1 revealed that it is probably not linked to levels, but to a side effect in the `expand_head` function in `ctype.ml` : https://github.com/ocaml/ocaml/blob/addec6564b1246b9d03ac33fd866aeacda5837d8/typing/ctype.ml#L3828-L3829 
Here, debug printing shows that the second line **mutates** the content of `t1'`, the result of expanding `t1`. While the expansion initially returns `int` (the correct result), the second line changes it back to `bool_t`, while returning also `int` for `t2'`. Then, the pattern match that follows fail. 
So maybe something like "Side effect in type expansion leads to improper treatment of type constraints" ?

**Comment by smuenzel** [comment]
Ah I guess then it makes sense that the "Keep expansion" pr #11648 fixes this issues. Hopefully it's not just an incidental fix due to changing the way expansions are tracked

**Comment by phink** [comment]
@clementblaudeau thanks, done.

**Comment by smuenzel** [comment]
github-actions seems to not consider the commits referencing the issue as being active. but the fix is in progress!

**Comment by garrigue** [comment]
Fixed by #11648
