### ISSUE TITLE
ocamldoc manpage generator does not preserve formatting in {[ ]}

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6596]
**Original bug ID:** 6596
**Reporter:** @whitequark
**Assigned to:** @zoggy
**Status:** assigned (set by @damiendoligez on 2015-01-16T16:24:21Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.03.0+dev / +beta1
**Category:** ocamldoc

## Bug description

As I understand it, {[ ]} is intended for e.g. code samples. As such, in HTML documentation, it's written down using < pre >, and everything is fine. However, in manpages, it ignores newlines and whitespace and all the text smashes into a single line, making the sample unreadable.

**Comment by whitequark** [comment]
Still an issue.

**Comment by Octachron** [comment]
This was fixed in #9113 .

**Comment by xavierleroy** [comment]
@whitequark: could you please check that something is "still an issue" before commenting?

**Comment by whitequark** [comment]
@xavierleroy Could you please not threaten to automatically close, for the most part, valid issues in bulk simply because they were inactive for a year? This is a hostile policy and I will deal with it the way I deal with hostile policies.

**Comment by whitequark** [comment]
And to be clear, doing automatic triage like this once, or triaging manually with the same request would not be a problem. It is the part where this policy creates endless make-work for reporters each year that makes it hostile.
