### ISSUE TITLE
Various C compilation failures for packages that are using caml/compatiblity.h

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#9160]
I was looking at the result for `4.10` in last week's check on [check.ocamllabs.io](http://check.ocamllabs.io) and a lot of important packages appear to fail with the same error coming from `caml/compatiblity.h`. Here are the full logs:

* coq: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/coq.8.10.1
* lablgtk3: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/lablgtk3.3.0.beta6
* ocamlnet: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/ocamlnet.4.1.6
* lablgtk: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/lablgtk.2.18.8
* ocurl: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/ocurl.0.9.0
* grenier: http://check.ocamllabs.io/log/1574696611-eec32e8750d18eaf1eb0d416d0f03b9e0f1df40f/4.10/bad/grenier.0.8

All of them have similar failures, for instance in Coq:
```
- In file included from /home/opam/.opam/4.10.0+trunk/lib/ocaml/caml/memory.h:22,
-                  from coq_interp.c:19:
- /home/opam/.opam/4.10.0+trunk/lib/ocaml/caml/compatibility.h:247:30: error: expected ')' before '->' token
-   247 | #define young_ptr (Caml_state->_young_ptr)
-       |                              ^~
- coq_gc.h:20:18: note: in expansion of macro 'young_ptr'
-    20 | CAMLextern char *young_ptr;
-       |                  ^~~~~~~~~
- /home/opam/.opam/4.10.0+trunk/lib/ocaml/caml/compatibility.h:248:32: error: expected ')' before '->' token
-   248 | #define young_limit (Caml_state->_young_limit)
-       |                                ^~
- coq_gc.h:21:18: note: in expansion of macro 'young_limit'
-    21 | CAMLextern char *young_limit;
-       |                  ^~~~~~~~~~~
- make[1]: *** [Makefile.build:340: kernel/byterun/coq_memory.o] Error 2
- make[1]: *** Waiting for unfinished jobs....
- make[1]: *** [Makefile.build:340: kernel/byterun/coq_interp.o] Error 2
```
I'm not sure this issue has been fixed in the last week or if it's related to https://github.com/ocaml/ocaml/issues/9014 or https://github.com/ocaml/ocaml/issues/9013 but just in case it's not I'm making this issue. If it has been fixed, is unrelated to the compiler or if it's already tracked tell me and I'll close this issue.

**Comment by Octachron** [comment]
This should be fixed by #9143 that was merged today in 4.10 .

**Comment by garrigue** [comment]
#9143 does not fix all of those: all these packages should remove their `CAMLextern` declarations for `young_*`.
Or do we have a plan to fix this problem in another way?

**Comment by garrigue** [comment]
More precisely, #9143 only fixes the fact `caml_young_*` was broken for uses outside of the compiler.
It does nothing to mitigate the fact `young_*` now expand to pointers inside a structure, and as such cannot be re-declared as `char *`.

**Comment by gasche** [comment]
See #9014 where the issues where reported, #9115 which fixes some of them (not `ref_table`), #8940 (which started fixing the somewhat broken state of) #8713.

**Comment by gadmm** [comment]
I do not see a perfectly backwards-compatible approach. (Does anyone else?) If so the best one can do is make it as simple for the user as possible:

1. Document systematic transition steps that can be taken, e.g.

```diff
+#include <caml/version.h>
 ...
+#if OCAML_VERSION < 41000
 CAMLextern char *young_limit;
+#endif
```

2. (optional) Propose a macro in `compatibility.h` that does all that automatically

```diff
-CAMLextern char *young_limit;
+Caml_declare_state_field(char *young_limit);
```

Let me know if you are interested in the latter.

This is my naive take, let me know if you see a better solution.

**Comment by stedolan** [comment]
The reasonably backwards-compatible approach to accessing `young_limit` is:
```
#include <caml/minor_gc.h>
```
This will work back to 4.04, when the `minor_gc.h` header began to be installed (#656). This is a more reliable approach than redeclaring the runtime's variables.

(For code that wants to support 4.03 and earlier, there's no alternative but `#if OCAML_VERSION < 40400`)

**Comment by gadmm** [comment]
I am not sure I prefer it:
* It does not do anything in the future for that purpose since it no longer declares young_limit.
* There seems to be an agreement that because it is not documented, it must be treated as an internal interface. If you want to refer to it in public documentation, I think we need to wrap it inside `#ifdef CAML_INTERNALS`.
* Are young_limit/ptr the only ones?

A plain `#if OCAML_VERSION < 41000` is also useful to document what is the modern part of the code and is helpful for mechanically removing obsolete code a few years later.

**Comment by gadmm** [comment]
I think the part where the user has to add `#if OCAML_VERSION < 41000` is fine, because (AFAIU) it only happens if they touch internals.

What could be helpful is some centralised documentation for migration (either official or on some page/wiki). It is needed eventually for multicore, and I think it is the right time to start it.

**Comment by gadmm** [comment]
Now here is an unintended consequence of the new `caml/compatibility.h`: apart from `caml_compare_unordered`, all these runtime state variables could only be accessed by defining `CAML_INTERNALS` before (if we forget `extern` definitions for a second). Now it is all as if they are public (meaning there is at least missing documentation stating that they are internal, and a mechanism to prevent mixing internal and supported code). A solution would be to enclose relevant compatibility macro definitions inside `#ifdef CAML_INTERNALS`. @stedolan, does this sound good to you? (In that case I would not touch the short name definitions (`#ifndef CAML_NAME_SPACE`).) A more forward-looking alternative is to even make `Caml_state` itself internal, and provide a proper interface to query and change caml_compare_unordered at the cost of a theoretical breaking change.
