### ISSUE TITLE
Incorrect characters in the 'plain-text' ref manual

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/ocaml#9242]
Screenshot (with releases v4.07 - v4.08 - v4.09 - v4.10).
First pb with release 4.08.

![plain_text](https://user-images.githubusercontent.com/4992512/72258725-143a5d00-360f-11ea-80f6-68a704ad4eb4.png)

**Comment by nojb** [comment]
It looks like the `.txt` in versions > 4.07 are encoded in UTF-8, as opposed to Latin-1 in 4.07; you should be able to check this by reverting your buffer as UTF-8. You can typically do this in `emacs` by doing `M-x revert-buffer-with-coding-system` and choosing `utf-8`.

**Comment by Octachron** [comment]
Those character are correct, they are indeed just utf8-encoded since 4.08 . It seems however that there is some other ill-formed characters somewhere else; and *they* might trigger this degraded display mode.

**Comment by Octachron** [comment]
Typically, the true error seems to be an invalid character after:

>    Iterators on two arrays

**Comment by Fourchaux** [comment]
Lines with ill-formed characters (File ocaml-4.08-refman.txt).

In the Section 26.15 Module Float:
L 29321 - 29370 - 29391 - 29427 - 29478 - 29519

Plus:
L 30614 - 35194 - 38874

**Comment by Octachron** [comment]
It turns out that this was a bug within hevea. The bug has been fixed, and I will push an updated version on the text manual to ocaml.org .

**Comment by Octachron** [comment]
The issue is no longer present in the 4.11 manual.

**Comment by Fourchaux** [comment]
Sorry to re-open this issue, but I still have some problems.


e.g. Line 32106 or Line 32127
of https://caml.inria.fr/pub/distrib/ocaml-4.11/ocaml-4.11-refman.txt :  

![ocaml-4 11-refman_errors](https://user-images.githubusercontent.com/4992512/90796593-ceb1e100-e30f-11ea-9d7b-e1cc95ba94a2.png)

BTW, doing a simple whitespace cleanup on the file will delete 90.5 Kio.

**Comment by Octachron** [comment]
Indeed. I had forgotten that the version of hevea with the fix has not been published yet. I will push a version of the file with the master version of hevea. Thanks for the report!
